In [26]:
class CustomLR:

    def __init__(self):
        self.m = None
        self.b = None

    def fit(self,X_train,y_train):

        num = 0
        den = 0

        for i in range(X_train.shape[0]):

            num = num + ((X_train[i] - X_train.mean())*(y_train[i] - y_train.mean()))
            den = den + ((X_train[i] - X_train.mean())*(X_train[i] - X_train.mean()))

        self.m = num/den
        self.b = y_train.mean() - (self.m * X_train.mean())
        print(self.m)
        print(self.b)

    def predict(self,X_test):

        # print(X_test)

        return self.m * X_test + self.b

In [1]:
import numpy as np
import pandas as pd


In [14]:
df = pd.read_csv('house-prices.csv')

In [15]:
X = df.iloc[:, 0].values
y = df.iloc[:, 1].values

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2,random_state=42)

In [27]:
lr = CustomLR()

In [18]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

In [19]:
X_train_scaled = scaler.fit_transform(X_train.reshape(-1, 1))

X_test_scaled = scaler.transform(X_test.reshape(-1, 1))


In [20]:
X_train_scaled

array([[0.33809882],
       [0.74617507],
       [0.51291698],
       [0.31527464],
       [0.77577126],
       [0.5314773 ],
       [0.34462002],
       [0.01630298],
       [0.14472034],
       [0.10985704],
       [0.50363682],
       [0.39804364],
       [0.32580888],
       [0.24203662],
       [0.15199398],
       [0.61399549],
       [0.43892651],
       [0.14647605],
       [0.0215701 ],
       [0.40130424],
       [0.77878104],
       [0.83872586],
       [0.13819915],
       [0.91522448],
       [0.49034362],
       [0.68221721],
       [0.44971156],
       [0.23952847],
       [0.46877351],
       [0.74742914],
       [0.67870579],
       [0.80712315],
       [0.30348633],
       [0.496614  ],
       [0.31176323],
       [0.26460998],
       [0.45823928],
       [0.46927514],
       [0.67795335],
       [0.44795586],
       [0.44670178],
       [0.51968899],
       [0.8096313 ],
       [0.69224981],
       [0.06997743],
       [0.5397542 ],
       [0.07399047],
       [0.913

In [22]:
y_test

array([395448.27, 157565.03, 462582.96, 485216.17, 275271.61, 582865.03,
       413268.13,  98776.88, 217675.99, 534595.94, 364990.87, 208908.53,
       568635.53, 249278.5 , 153209.25, 243591.66, 412560.7 , 152969.41,
        20292.51, 612943.67, 255577.76, 464286.61, 415591.38, 236500.31,
       224677.82, 467640.52, 617197.77, 363690.99, 359025.9 , 435112.56,
       448653.95, 510378.74, 329446.28, 450351.93, 467651.36, 329298.37,
       164163.36, 334615.98, 347463.39, 439133.99, 441507.24, 231723.39,
       278402.38, 325723.45, 208532.31, 334986.53, 239410.88, 508334.5 ,
       448401.88, 601680.67, 223915.47,  64010.73, 300341.05, 253506.58,
        50333.29, 510138.29, 576870.01, 610494.96, 340826.17, 115944.7 ,
       238640.49, 563140.45, 374242.08, 403818.83, 223339.68, 420831.23,
        14063.36, 559713.46, 448060.85, 487993.45, 344229.57, 440838.46,
       512088.71, 582681.03, 552801.05, 276791.06, 561509.43, 329510.96,
       320943.21, 318845.48, 370702.23, 329671.61, 

In [28]:
lr.fit(X_train_scaled,y_train)

[379674.15395957]
[160563.98001189]


In [29]:
print(lr.predict(X_test_scaled)[0])

[424155.16590607]


In [30]:
print(lr.predict(X_test_scaled)[0:5])

[[424155.16590607]
 [217034.20155642]
 [451580.83842686]
 [349877.30282896]
 [263695.93605358]]
